-- =============================================================================
-- DEVELOPMENT SEED DATA — SAMPLE PAYMENT SETTINGS
-- =============================================================================
--
-- Target tables : public.payment_settings, public.admin_settings
--                 (created by supabase/migrations/003_create_payment_settings.sql)
-- Purpose       : Give the enrollment payment step something to render during
--                 development, so the flow can be walked end to end without wiring
--                 up a real bank account.
--
-- THIS FILE IS NOT A MIGRATION.
-- It lives in supabase/seed/ rather than supabase/migrations/ so it is never picked
-- up by the migration chain and applied to production. Run it by hand against a
-- development project only.
--
-- WHAT THIS FILE DOES NOT DO
--   * It does not create, drop or alter any table, column, index, trigger or
--     constraint.
--   * It does not create, drop or alter any RLS policy.
--   * It writes to exactly two tables: public.payment_settings and
--     public.admin_settings. It never touches public.enrollments.
--
-- CONTENT DISCLAIMER
--   THE BANK DETAILS BELOW ARE FICTIONAL AND DELIBERATELY INVALID.
--   The account number is a placeholder digit string, the bank is invented, and the
--   account name is prefixed "[Sample]". Nobody can be paid using these values, and
--   they must never be presented to a real student. Before this project accepts a
--   real payment, replace the active row with genuine details supplied by the
--   business — do not edit this file to hold them, because seed files are committed
--   to the repository.
--
--   The support number is the existing public support line already compiled into the
--   frontend (src/lib/constants/homepage.ts), not a new contact detail.
--
-- IDEMPOTENCY
--   Re-running this file is safe and will not create duplicates or trip the
--   single-active-row index. Both statements delete the rows they are about to write
--   first, inside the same transaction, so the end state is exactly one active
--   payment_settings row and exactly one admin_settings row regardless of how many
--   times the file has been run before.
--
--   updated_at is intentionally not written: the *_set_updated_at triggers from the
--   migration own that column.
--
-- TEARDOWN
--   See the commented block at the bottom of this file.
-- =============================================================================

begin;

-- payment_settings carries a partial unique index on (is_active) where is_active,
-- so "insert the active row" has to start from a clean slate rather than relying on
-- `on conflict`: there is no natural key to conflict against.
delete from public.payment_settings
where account_name like '[Sample]%';

insert into public.payment_settings (
  bank_name,
  account_name,
  account_number,
  additional_details,
  currency,
  payment_instructions,
  review_window_hours,
  support_whatsapp_number,
  is_active
)
values (
  '[Sample] Development Bank',
  '[Sample] Drizzypips Academy Ltd',
  -- Placeholder digits, not a routable account number.
  '0000000000',
  'Sample development data — this account does not exist and cannot receive payment. '
    || 'Replace with real details supplied by the business before going live.',
  'NGN',
  'Transfer the exact course fee to the account above, then upload a clear photo or '
    || 'PDF of your payment receipt. Use your order reference as the transfer narration '
    || 'if your bank allows it. Your enrollment is confirmed once we have checked the '
    || 'payment against our records.',
  24,
  '+2349035853860',
  true
);

-- admin_settings is constrained to a single row by its boolean primary key (the check
-- permits only `true`, and the key permits it once), so the same delete-then-insert
-- shape applies.
delete from public.admin_settings;

insert into public.admin_settings (
  notification_email,
  enrollment_enabled,
  enrollment_paused_message
)
values (
  -- example.com is reserved by RFC 2606 and can never receive mail.
  'sample-admin@example.com',
  true,
  'Enrollments are paused for scheduled maintenance. Please check back shortly.'
);

commit;

-- =============================================================================
-- VERIFICATION
-- =============================================================================
-- Expect exactly one row from each.
--
--   select bank_name, account_name, currency, is_active from public.payment_settings;
--   select notification_email, enrollment_enabled from public.admin_settings;
--
-- Anonymous visibility check — run with the anon key; should return the active row
-- for payment_settings and zero rows for admin_settings:
--
--   select count(*) from public.payment_settings;  -- expect 1
--   select count(*) from public.admin_settings;    -- expect 0 (no anon policy)
--
-- =============================================================================
-- TEARDOWN
-- =============================================================================
-- Removes only what this file created.
--
--   delete from public.payment_settings where account_name like '[Sample]%';
--   delete from public.admin_settings where notification_email = 'sample-admin@example.com';
--
-- =============================================================================
